import os
import json
from reportlab.lib.colors import HexColor
import pandas as pd

from datetime import datetime
from reportlab.platypus import (HRFlowable, SimpleDocTemplate,Paragraph,Spacer,Table, TableStyle)
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4


class ReportController:
    def __init__(self, evidence_path):
        self.evidence_path = evidence_path

        self.files = [
            "history.csv",
            "downloads.csv",
            "cookies.csv",
            "logins.csv",
            "caches.csv",
            "search_terms.csv",
            "bookmarks.csv",
            "autofill.csv",
            "sessions.csv",
            "top_sites.csv"
        ]

        self.table_style =  TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ])

    # LOAD ALL CSV FILES
    def load_all_data(self):
        report_data = {}

        for file in self.files:
            file_path = os.path.join(
                self.evidence_path,
                file
            )

            key = file.replace(".csv", "")

            if os.path.exists(file_path):
                try:
                    df = pd.read_csv(file_path)
                    report_data[key] = df
                except:
                    report_data[key] = pd.DataFrame()

        return report_data
    
    def artifact_summary(self, data):
        summary_data = [
            ["Artefact Type", "Findings"]
        ]

        for section, df in data.items():
            findings_count = 0

            try:
                findings_count = len(df.index)
            except Exception:
                findings_count = 0

            summary_data.append([
                section.replace("_", " ").title(),
                str(findings_count)
            ])

        summary_table = Table(
            summary_data,
            colWidths=[250, 120],
            repeatRows=1
        )
        summary_table.setStyle(self.table_style)

        return summary_table

    def add_page_header_footer(seld, canvas, doc):
        canvas.saveState()
        width, height = A4

        # Header
        canvas.setFont("Helvetica-Bold", 11)
        canvas.drawString(30,height - 20,"CRAFT - Cross Browser Artifact Forensic Tool")
        canvas.setFont("Helvetica", 8)

        # Footer
        canvas.setFont("Helvetica", 8)
        canvas.drawString(30,15,"Generated by: CRAFT - Cross Browser Artifact Forensic Tooll")
        canvas.drawRightString(width - 30,15,f"Page {doc.page}")
        canvas.restoreState()

    def export_full_pdf(self, output_file):
        data = self.load_all_data()
        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            "TitleStyle",
            parent=styles["Title"],
            textColor=HexColor("#1591DC"),
            fontSize=24,
            leading=28,
            spaceAfter=10
        )

        heading_style = ParagraphStyle(
            "HeadingStyle",
            parent=styles["Heading2"],
            textColor=HexColor("#1591DC"),
            fontSize=16,
            leading=20,
            spaceAfter=2
        )

        cell_style = ParagraphStyle("CellStyle",parent=styles["Normal"],fontSize=8,leading=10,wordWrap="CJK")
        elements = []

        # Title
        elements.append(Paragraph("CRAFT Forensic Report", title_style))
        elements.append(Spacer(1, 2))
        elements.append(HRFlowable(width="100%",thickness=0.7,color=HexColor("#1591DC")))
        elements.append(Spacer(0, 1))
        generated_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        elements.append(Paragraph(f"<font color='grey'>Report Generated on: {generated_date}</font>",styles["Normal"]))

        #Summary
        elements.append(Paragraph("Findings Summary",heading_style))
        elements.append(Spacer(1, 6))
        elements.append(self.artifact_summary(data))
        elements.append(Spacer(1, 20))

        for section, df in data.items():
            elements.append(Paragraph(section.replace("_", " ").title(),heading_style))
            elements.append(Spacer(0, 1))

            if df.empty:
                elements.append(Paragraph("No data found", styles["Normal"]))
                elements.append(Spacer(0, 15))
                continue

            # limit rows for readability
            df = df.head(50)
            headers = [
                Paragraph(str(col), cell_style)
                for col in df.columns.tolist()
            ]

            rows = []
            for row in df.astype(str).values.tolist():
                wrapped_row = [
                    Paragraph(str(value), cell_style)
                    for value in row
                ]
                rows.append(wrapped_row)
            table_data = [headers] + rows

            pdf = SimpleDocTemplate(
                output_file,
                pagesize=A4,
                leftMargin=32,
                rightMargin=32,
                topMargin=32,
                bottomMargin=32
            )

            # A4 usable width
            page_width = A4[0] - pdf.leftMargin - pdf.rightMargin
            max_columns_width = page_width

            col_count = len(df.columns)
            col_width = max_columns_width / col_count
            col_widths = [col_width] * col_count

            table = Table(table_data, colWidths=col_widths, repeatRows=1)
            table.setStyle(self.table_style)

            elements.append(table)
            elements.append(Spacer(1, 20))

        pdf.build(
            elements,
            onFirstPage=self.add_page_header_footer,
            onLaterPages=self.add_page_header_footer
        )

    def export_full_json(self, output_file):
        data = self.load_all_data()
        final_data = {}
        for section, df in data.items():
            final_data[section] = df.to_dict(
                orient="records"
            )

        with open(output_file, "w", encoding="utf-8") as f:
            json.dump(final_data,f,indent=4,ensure_ascii=False)

    def export_full_html(self, output_file):
        data = self.load_all_data()
        html = "<h1>CRAFT Forensic Report</h1>"
        for section, df in data.items():
            html += f"<h2>{section.upper()}</h2>"
            if df.empty:
                html += "<p>No data found</p>"
            else:
                html += df.to_html(index=False)
                
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(html)

    def export_full_csv(self, output_file):
        data = self.load_all_data()
        combined = pd.DataFrame()

        for section, df in data.items():
            if not df.empty:
                df = df.copy()
                df.insert(0,"Artifact Type",section)
                combined = pd.concat([combined, df],ignore_index=True)

        combined.to_csv(
            output_file,
            index=False,
            encoding="utf-8-sig"
        )